name: unsplash
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_downloader: ^1.8.4
  permission_handler: ^10.0.2
  flutter_cache_manager: ^3.3.0
  provider: ^6.0.3
  equatable: ^2.0.5
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.5
  flutter_launcher_icons: ^0.10.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/files/topics.json
    - assets/images/